apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-parser-apache-tika
  labels:
    app: pdf-parser-apache-tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-parser-apache-tika
  template:
    metadata:
      labels:
        app: pdf-parser-apache-tika
    spec:
      containers:
        - name: pdf-parser-apache-tika
          image: apache/tika
          ports:
            - containerPort: 9998
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-parser-apache-tika-service
spec:
  selector:
    app: pdf-parser-apache-tika
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998