apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-parser-ui
  labels:
    app: pdf-parser-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-parser-ui
  template:
    metadata:
      labels:
        app: pdf-parser-ui
    spec:
      containers:
        - name: pdf-parser-ui
          image: danielyandev/pdf-parser-ui:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
          livenessProbe:
            httpGet:
              path: /index.html
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.html
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-parser-ui-service
spec:
  selector:
    app: pdf-parser-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000