version: '3.7'

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/ui'
      - '/ui/node_modules'
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
